/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTrainerIndexRouteImport } from './routes/_authenticated/trainer/index'
import { Route as AuthenticatedClientIndexRouteImport } from './routes/_authenticated/client/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedTrainerProfileRouteImport } from './routes/_authenticated/trainer/profile'
import { Route as AuthenticatedTrainerEarningsRouteImport } from './routes/_authenticated/trainer/earnings'
import { Route as AuthenticatedTrainerClientsRouteImport } from './routes/_authenticated/trainer/clients'
import { Route as AuthenticatedTrainerBookingsRouteImport } from './routes/_authenticated/trainer/bookings'
import { Route as AuthenticatedTrainerAvailabilityRouteImport } from './routes/_authenticated/trainer/availability'
import { Route as AuthenticatedClientProfileRouteImport } from './routes/_authenticated/client/profile'
import { Route as AuthenticatedClientPoseRouteImport } from './routes/_authenticated/client/pose'
import { Route as AuthenticatedClientMatchesRouteImport } from './routes/_authenticated/client/matches'
import { Route as AuthenticatedClientBookingsRouteImport } from './routes/_authenticated/client/bookings'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTrainersRouteImport } from './routes/_authenticated/admin/trainers'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrainerIndexRoute =
  AuthenticatedTrainerIndexRouteImport.update({
    id: '/trainer/',
    path: '/trainer/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientIndexRoute =
  AuthenticatedClientIndexRouteImport.update({
    id: '/client/',
    path: '/client/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrainerProfileRoute =
  AuthenticatedTrainerProfileRouteImport.update({
    id: '/trainer/profile',
    path: '/trainer/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTrainerEarningsRoute =
  AuthenticatedTrainerEarningsRouteImport.update({
    id: '/trainer/earnings',
    path: '/trainer/earnings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTrainerClientsRoute =
  AuthenticatedTrainerClientsRouteImport.update({
    id: '/trainer/clients',
    path: '/trainer/clients',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTrainerBookingsRoute =
  AuthenticatedTrainerBookingsRouteImport.update({
    id: '/trainer/bookings',
    path: '/trainer/bookings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTrainerAvailabilityRoute =
  AuthenticatedTrainerAvailabilityRouteImport.update({
    id: '/trainer/availability',
    path: '/trainer/availability',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientProfileRoute =
  AuthenticatedClientProfileRouteImport.update({
    id: '/client/profile',
    path: '/client/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientPoseRoute = AuthenticatedClientPoseRouteImport.update({
  id: '/client/pose',
  path: '/client/pose',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientMatchesRoute =
  AuthenticatedClientMatchesRouteImport.update({
    id: '/client/matches',
    path: '/client/matches',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientBookingsRoute =
  AuthenticatedClientBookingsRouteImport.update({
    id: '/client/bookings',
    path: '/client/bookings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminTrainersRoute =
  AuthenticatedAdminTrainersRouteImport.update({
    id: '/admin/trainers',
    path: '/admin/trainers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/trainers': typeof AuthenticatedAdminTrainersRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/client/bookings': typeof AuthenticatedClientBookingsRoute
  '/client/matches': typeof AuthenticatedClientMatchesRoute
  '/client/pose': typeof AuthenticatedClientPoseRoute
  '/client/profile': typeof AuthenticatedClientProfileRoute
  '/trainer/availability': typeof AuthenticatedTrainerAvailabilityRoute
  '/trainer/bookings': typeof AuthenticatedTrainerBookingsRoute
  '/trainer/clients': typeof AuthenticatedTrainerClientsRoute
  '/trainer/earnings': typeof AuthenticatedTrainerEarningsRoute
  '/trainer/profile': typeof AuthenticatedTrainerProfileRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/client/': typeof AuthenticatedClientIndexRoute
  '/trainer/': typeof AuthenticatedTrainerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/trainers': typeof AuthenticatedAdminTrainersRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/client/bookings': typeof AuthenticatedClientBookingsRoute
  '/client/matches': typeof AuthenticatedClientMatchesRoute
  '/client/pose': typeof AuthenticatedClientPoseRoute
  '/client/profile': typeof AuthenticatedClientProfileRoute
  '/trainer/availability': typeof AuthenticatedTrainerAvailabilityRoute
  '/trainer/bookings': typeof AuthenticatedTrainerBookingsRoute
  '/trainer/clients': typeof AuthenticatedTrainerClientsRoute
  '/trainer/earnings': typeof AuthenticatedTrainerEarningsRoute
  '/trainer/profile': typeof AuthenticatedTrainerProfileRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/client': typeof AuthenticatedClientIndexRoute
  '/trainer': typeof AuthenticatedTrainerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/admin/trainers': typeof AuthenticatedAdminTrainersRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/client/bookings': typeof AuthenticatedClientBookingsRoute
  '/_authenticated/client/matches': typeof AuthenticatedClientMatchesRoute
  '/_authenticated/client/pose': typeof AuthenticatedClientPoseRoute
  '/_authenticated/client/profile': typeof AuthenticatedClientProfileRoute
  '/_authenticated/trainer/availability': typeof AuthenticatedTrainerAvailabilityRoute
  '/_authenticated/trainer/bookings': typeof AuthenticatedTrainerBookingsRoute
  '/_authenticated/trainer/clients': typeof AuthenticatedTrainerClientsRoute
  '/_authenticated/trainer/earnings': typeof AuthenticatedTrainerEarningsRoute
  '/_authenticated/trainer/profile': typeof AuthenticatedTrainerProfileRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/client/': typeof AuthenticatedClientIndexRoute
  '/_authenticated/trainer/': typeof AuthenticatedTrainerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/admin/trainers'
    | '/admin/users'
    | '/client/bookings'
    | '/client/matches'
    | '/client/pose'
    | '/client/profile'
    | '/trainer/availability'
    | '/trainer/bookings'
    | '/trainer/clients'
    | '/trainer/earnings'
    | '/trainer/profile'
    | '/admin/'
    | '/client/'
    | '/trainer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/admin/trainers'
    | '/admin/users'
    | '/client/bookings'
    | '/client/matches'
    | '/client/pose'
    | '/client/profile'
    | '/trainer/availability'
    | '/trainer/bookings'
    | '/trainer/clients'
    | '/trainer/earnings'
    | '/trainer/profile'
    | '/admin'
    | '/client'
    | '/trainer'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/login'
    | '/register'
    | '/_authenticated/admin/trainers'
    | '/_authenticated/admin/users'
    | '/_authenticated/client/bookings'
    | '/_authenticated/client/matches'
    | '/_authenticated/client/pose'
    | '/_authenticated/client/profile'
    | '/_authenticated/trainer/availability'
    | '/_authenticated/trainer/bookings'
    | '/_authenticated/trainer/clients'
    | '/_authenticated/trainer/earnings'
    | '/_authenticated/trainer/profile'
    | '/_authenticated/admin/'
    | '/_authenticated/client/'
    | '/_authenticated/trainer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trainer/': {
      id: '/_authenticated/trainer/'
      path: '/trainer'
      fullPath: '/trainer/'
      preLoaderRoute: typeof AuthenticatedTrainerIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client/': {
      id: '/_authenticated/client/'
      path: '/client'
      fullPath: '/client/'
      preLoaderRoute: typeof AuthenticatedClientIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trainer/profile': {
      id: '/_authenticated/trainer/profile'
      path: '/trainer/profile'
      fullPath: '/trainer/profile'
      preLoaderRoute: typeof AuthenticatedTrainerProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trainer/earnings': {
      id: '/_authenticated/trainer/earnings'
      path: '/trainer/earnings'
      fullPath: '/trainer/earnings'
      preLoaderRoute: typeof AuthenticatedTrainerEarningsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trainer/clients': {
      id: '/_authenticated/trainer/clients'
      path: '/trainer/clients'
      fullPath: '/trainer/clients'
      preLoaderRoute: typeof AuthenticatedTrainerClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trainer/bookings': {
      id: '/_authenticated/trainer/bookings'
      path: '/trainer/bookings'
      fullPath: '/trainer/bookings'
      preLoaderRoute: typeof AuthenticatedTrainerBookingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trainer/availability': {
      id: '/_authenticated/trainer/availability'
      path: '/trainer/availability'
      fullPath: '/trainer/availability'
      preLoaderRoute: typeof AuthenticatedTrainerAvailabilityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client/profile': {
      id: '/_authenticated/client/profile'
      path: '/client/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof AuthenticatedClientProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client/pose': {
      id: '/_authenticated/client/pose'
      path: '/client/pose'
      fullPath: '/client/pose'
      preLoaderRoute: typeof AuthenticatedClientPoseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client/matches': {
      id: '/_authenticated/client/matches'
      path: '/client/matches'
      fullPath: '/client/matches'
      preLoaderRoute: typeof AuthenticatedClientMatchesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client/bookings': {
      id: '/_authenticated/client/bookings'
      path: '/client/bookings'
      fullPath: '/client/bookings'
      preLoaderRoute: typeof AuthenticatedClientBookingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/trainers': {
      id: '/_authenticated/admin/trainers'
      path: '/admin/trainers'
      fullPath: '/admin/trainers'
      preLoaderRoute: typeof AuthenticatedAdminTrainersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminTrainersRoute: typeof AuthenticatedAdminTrainersRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedClientBookingsRoute: typeof AuthenticatedClientBookingsRoute
  AuthenticatedClientMatchesRoute: typeof AuthenticatedClientMatchesRoute
  AuthenticatedClientPoseRoute: typeof AuthenticatedClientPoseRoute
  AuthenticatedClientProfileRoute: typeof AuthenticatedClientProfileRoute
  AuthenticatedTrainerAvailabilityRoute: typeof AuthenticatedTrainerAvailabilityRoute
  AuthenticatedTrainerBookingsRoute: typeof AuthenticatedTrainerBookingsRoute
  AuthenticatedTrainerClientsRoute: typeof AuthenticatedTrainerClientsRoute
  AuthenticatedTrainerEarningsRoute: typeof AuthenticatedTrainerEarningsRoute
  AuthenticatedTrainerProfileRoute: typeof AuthenticatedTrainerProfileRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedClientIndexRoute: typeof AuthenticatedClientIndexRoute
  AuthenticatedTrainerIndexRoute: typeof AuthenticatedTrainerIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminTrainersRoute: AuthenticatedAdminTrainersRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedClientBookingsRoute: AuthenticatedClientBookingsRoute,
  AuthenticatedClientMatchesRoute: AuthenticatedClientMatchesRoute,
  AuthenticatedClientPoseRoute: AuthenticatedClientPoseRoute,
  AuthenticatedClientProfileRoute: AuthenticatedClientProfileRoute,
  AuthenticatedTrainerAvailabilityRoute: AuthenticatedTrainerAvailabilityRoute,
  AuthenticatedTrainerBookingsRoute: AuthenticatedTrainerBookingsRoute,
  AuthenticatedTrainerClientsRoute: AuthenticatedTrainerClientsRoute,
  AuthenticatedTrainerEarningsRoute: AuthenticatedTrainerEarningsRoute,
  AuthenticatedTrainerProfileRoute: AuthenticatedTrainerProfileRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedClientIndexRoute: AuthenticatedClientIndexRoute,
  AuthenticatedTrainerIndexRoute: AuthenticatedTrainerIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
